name: Update Homebrew
on: 
  release:
    types: [created]

jobs:
  update-core:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.PENNY_APP_ID }}
          private-key: ${{ secrets.PENNY_APP_PRIVATE_KEY }}
          owner: vapor

      - name: Add path
        run: echo /home/linuxbrew/.linuxbrew/bin >>"${GITHUB_PATH}"
        
      - name: Update Homebrew formula
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ steps.get-token.outputs.token }}
        run: |
          git config --global user.name 'Penny[bot]'
          git config --global user.email '360798+penny[bot]@vapor.codes'
          brew tap homebrew/core
          brew bump-formula-pr \
            --no-audit \
            --no-browse \
            --fork-org=vapor \
            --tag="${GITHUB_REF_NAME}" \
            --revision="${GITHUB_SHA}" \
            
